/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallSessionIdRouteImport } from './routes/call.$sessionId'
import { Route as CallNewRouteImport } from './routes/call.new'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallSessionIdRoute = CallSessionIdRouteImport.update({
  id: '/call/$sessionId',
  path: '/call/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallNewRoute = CallNewRouteImport.update({
  id: '/call/new',
  path: '/call/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call/$sessionId': typeof CallSessionIdRoute
  '/call/new': typeof CallNewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call/$sessionId': typeof CallSessionIdRoute
  '/call/new': typeof CallNewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call/$sessionId': typeof CallSessionIdRoute
  '/call/new': typeof CallNewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/call/$sessionId' | '/call/new' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/call/$sessionId' | '/call/new' | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/call/$sessionId'
    | '/call/new'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallSessionIdRoute: typeof CallSessionIdRoute
  CallNewRoute: typeof CallNewRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$sessionId': {
      id: '/call/$sessionId'
      path: '/call/$sessionId'
      fullPath: '/call/$sessionId'
      preLoaderRoute: typeof CallSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/new': {
      id: '/call/new'
      path: '/call/new'
      fullPath: '/call/new'
      preLoaderRoute: typeof CallNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallSessionIdRoute: CallSessionIdRoute,
  CallNewRoute: CallNewRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
